### PR TITLE
Add SScript links and Funkin Cocoa to engines

### PR DESCRIPTION
**Pull request by TheWorldMachinima**
This PR adds links to my library SScript and adds Cocoa to engines section.

### CODE REVIEW

**Review by doggogit — APPROVED** [review]
Apologies for not linking your SScript fork. 😅

**Comment by EliteMasterEric** [comment]
If the engine isn't stable, it shouldn't be included on the list.

**Comment by TheWorldMachinima** [comment]
> Apologies for not linking your SScript fork. 😅

It's okay.


> If the engine isn't stable, it shouldn't be included on the list.
It is not unstable, it only has small bugs like sprite positioning. 
I can update the readme if you want.

**Comment by AltronMaxX** [comment]
Fun fact, Forever Engine Feather uses my SScript fork 🙃

**Pull request closed without merging**
