### PR TITLE
Attempt to fix empty issues

### PR DESCRIPTION
**Pull request by MemeHovy**
This PR attempts to fix the empty issues the bot keeps making as shown in the screenshot below.
Screenshot 2023-03-05 195147
Any feedback and criticism is appreciated 👍

### CODE REVIEW

**Comment by EliteMasterEric** [comment]
I don't see how this fixes anything either, the `continue` keyword returns to the beginning of a loop. If anything, this BREAKS non-empty issues.

**Comment by MemeHovy** [comment]
noted

**Comment by BombasticTom** [comment]
It's all good, people make mistakes. You could try again once you figure it out.

**Comment by MemeHovy** [comment]
aight

**Pull request closed without merging**
