### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MaybeMaru**
nerdy shit

### CODE REVIEW

**Review by BombasticTom — APPROVED** [review]
#professional

**Comment by ninjamuffin99** [comment]
nice, would u be able to revert the changes in the block quote section? those are my words in there, and i feel they should appear as I wrote them, grammatical errors and all!!! 

everything else looks nice heheh nice grammar-ing

**Comment by MaybeMaru** [comment]
yeah ofc

**Review by Burgerballs — APPROVED** [review]
minor-spelling-mistake

**Pull request merged**
