### PR TITLE
Added chromatic scale generator and moved polyphone soundfont editor

### PR DESCRIPTION
**Pull request by ColdlordXRepositories**
Everything’s is in the title
(I might only make pull request for this repository in my lifetime lol)
I apologize if I broke something, I was on mobile writing this in the GitHub app and I had to manually correct misspelled words SO MANY TIMES
anyways

### CODE REVIEW

**Comment by doggogit** [comment]
I've heard people say this chromatic generator is actual dogshit so I have no idea if this would be useful to add or not, will let other people share their opinion

**Comment by ColdlordXRepositories** [comment]
> I've heard people say this chromatic generator is actual dogshit so I have no idea if this would be useful to add or not, will let other people share their opinion 

It's worked for me every time, but I've only used it once, it might have random problems. Maybe.

**Comment by BombasticTom** [comment]
merge conflict moment

**Comment by ColdlordXRepositories** [comment]
> merge conflict moment

I'll fix it later

**Comment by BombasticTom** [comment]
huh

**Comment by ColdlordXRepositories** [comment]
> huh

yea I kinda gave up

**Pull request closed without merging**
