### PR TITLE
Added Animate Archive to the readme

### PR DESCRIPTION
**Pull request by xLinkmain**
Just added animate archive to the readme so people can get flash without pirating

### CODE REVIEW

**Review by doggogit — APPROVED** [review]

**Comment by MarkimusZer0** [comment]
Not sure whether AnimateArchive can be included as resource esp when Funkin Crew are like a company n shits

**Comment by doggogit** [comment]
> Not sure whether AnimateArchive can be included as resource esp when Funkin Crew are like a company n shits

I believe the older versions are free-of-use, as, Adobe would've already taken them down and I believe they fall in the category of abandonware, I'm not sure.

**Comment by MarkimusZer0** [comment]
> > Not sure whether AnimateArchive can be included as resource esp when Funkin Crew are like a company n shits
> 
> I believe the older versions are free-of-use, as, Adobe would've already taken them down and I believe they fall in the category of abandonware, I'm not sure.

I'm not certain bout the free of use, though they are as of current time not acquirable through normal means which is where my concerns mainly come from

**Comment by doggogit** [comment]
> > > Not sure whether AnimateArchive can be included as resource esp when Funkin Crew are like a company n shits
> > 
> > 
> > I believe the older versions are free-of-use, as, Adobe would've already taken them down and I believe they fall in the category of abandonware, I'm not sure.
> 
> I'm not certain bout the free of use, though they are as of current time not acquirable through normal means which is where my concerns mainly come from

[Found this on a forum post regarding the usage of older Flash/Animate versions](https://user-images.githubusercontent.com/115869532/214691501-0227e5f2-cf01-4136-9ecf-20c564fa2ae5.png).

[The replies under the abovementioned comment](https://user-images.githubusercontent.com/115869532/214691625-56de4951-aefb-4514-9f54-4ba507501de8.png).

[The forum post in question](https://community.adobe.com/t5/animate-discussions/is-this-outdated-free-version-of-flash-legal/m-p/9285774).

[There was a video linked, however, Adobe took it down with a copyright claim](https://user-images.githubusercontent.com/115869532/214691813-16b99f62-8c51-44ba-8b36-177ce7b53b0f.png). Just shows how serious they are.

**Comment by Catbrother-Everything** [comment]
I personally don't think this should be added as even the latest version on there (5.5) doesn't have export to spritesheet options

**Comment by doggogit** [comment]
> I personally don't think this should be added as even the latest version on there (5.5) doesn't have export to spritesheet options

The latest version is CS6, and since I've used that prior, it *does* have spritesheet exporting, but unfortunately no texture atlas.

**Comment by doggogit** [comment]
Yeah, you can't export them in 5.5, that fucking sucks.

We can specify that people can use CS6, if not, then this PR should be closed.

**Comment by ninjamuffin99** [comment]
I will say we don't wanna play too touchy with Adobe heheh, and also yeah, only adobe animate does the texture atlas stuff anyways!!!

**Comment by MarkimusZer0** [comment]
> 



> > I personally don't think this should be added as even the latest version on there (5.5) doesn't have export to spritesheet options
> 
> The latest version is CS6, and since I've used that prior, it _does_ have spritesheet exporting, but unfortunately no texture atlas.

Even if it does i think CS6 spritesheets can cause the game to crash when u put them in

**Comment by doggogit** [comment]
> > 
> 
> > > I personally don't think this should be added as even the latest version on there (5.5) doesn't have export to spritesheet options
> > 
> > 
> > The latest version is CS6, and since I've used that prior, it _does_ have spritesheet exporting, but unfortunately no texture atlas.
> 
> Even if it does i think CS6 spritesheets can cause the game to crash when u put them in



> > 
> 
> > > I personally don't think this should be added as even the latest version on there (5.5) doesn't have export to spritesheet options
> > 
> > 
> > The latest version is CS6, and since I've used that prior, it _does_ have spritesheet exporting, but unfortunately no texture atlas.
> 
> Even if it does i think CS6 spritesheets can cause the game to crash when u put them in

Damn that sucks

**Comment by PrincessMtH** [comment]
for the record, CS6 spritesheets are fine if you manually edit the encoding on the exported XML to UTF-8!!!

**Comment by doggogit** [comment]
> for the record, CS6 spritesheets are fine if you manually edit the encoding on the exported XML to UTF-8!!!

Oh, I see, cool

**Pull request closed without merging**
