### PR TITLE
Added trayfellow's fork of Newgrounds Port

### PR DESCRIPTION
**Pull request by DarkWeBareBears69**
This is the fork that what should've the not-yet-made week 7 build (desktop one, of course) look like.

### CODE REVIEW

**Comment by MarkimusZer0** [comment]
What unreleased week 7 build

**Comment by DarkWeBareBears69** [comment]
> What unreleased week 7 build

yes
(okay, for seriousness here, i just say that because i don't know if the week 7 build was made or not.)

**Comment by DarkWeBareBears69** [comment]
(And I edited the original post because of reasons. :/)

**Comment by doggogit** [comment]
So, this is essentially a fork of the NewgroundsPort, just with a few extra things. (maybe change the description of the PR to include these as its confusing to understand)

image

**Comment by DarkWeBareBears69** [comment]
Is this okay?
testing pull request

**Comment by DarkWeBareBears69** [comment]
Sorry, I'm not good at explaining sh*t.

**Comment by MarkimusZer0** [comment]
Idk this just seems like a slightly modified FNF-NewgroundsPort which I'm not sure would be fit considering NewgroundsPort is already in the resources

**Comment by doggogit** [comment]
> Idk this just seems like a slightly modified FNF-NewgroundsPort which I'm not sure would be fit considering NewgroundsPort is already in the resources

True to be fair

**Comment by trayfellow** [comment]
hi guys

**Comment by doggogit** [comment]
hello!

**Comment by ninjamuffin99** [comment]
we have week 7 source code out... so i will CLOSE this!! bwah!

**Pull request closed without merging**
