### PR TITLE
Add a Psych mod installing tutorial

### PR DESCRIPTION
**Pull request by MarkimusZer0**
Surprisingly have ran into people who didn't know how to put mods on psych so figured this would be a good addition to the resources

### CODE REVIEW

**Comment by ninjamuffin99** [comment]
just wanna quickly vet, this is from about a year ago, its all good and up to date and all that? idk how often the engine fuss update or whatevaaa heheh

**Comment by EliteMasterEric** [comment]
Looks good to me

Pro tip, the steps for installing mods in the upcoming base game update are exactly the same, just know that Psych mods won't work. and you'll have to manually remake them.

**Comment by MarkimusZer0** [comment]
> just wanna quickly vet, this is from about a year ago, its all good and up to date and all that? idk how often the engine fuss update or whatevaaa heheh

Eric has said it n all but yea this still works!!!
Psych hasn't changed that part about it in a tad (how mods are installed), tutorial may look a little old but it holds up pretty nicely

**Comment by Josephmorale** [comment]
please come back fnf mods mobile 1.0.4 plisss! In android I sad😢 now! please bring back fnf mods mobile 1.0.4 in android please 🥺

**Comment by Josephmorale** [comment]
People sad now 😞

**Comment by Josephmorale** [comment]
and people need it back 😞 please 🥺

**Comment by Josephmorale** [comment]
on mobile

**Pull request merged**
