### PR TITLE
Link week 6 source code as "stable" version

### PR DESCRIPTION
**Pull request by Burgerballs**
Corrects "Last updated for Week 6" to "Last updated for Week 7", while also linking the Week 6 source code as the stable version

### CODE REVIEW

**Review by EyeDaleHim — COMMENTED** [review]
`but it does not contain any of the things the Week 7 update has`

I'm a bit against this description, I might suggest something like `But it is a little unstable` or something on the Week 7 one.

**Review by EyeDaleHim — COMMENTED** [review]
I also disagree with this too, not the misspelling but I kind of threw you in the wrong direction.

Too lazy to do it myself too 😭

**Comment by ninjamuffin99** [comment]
merged but i changed to be JUST "updated for week 7" teehee, thanks!!

**Comment by Burgerballs** [comment]
> merged but i changed to be JUST "updated for week 7" teehee, thanks!!

Sounds all fine and silly to me, stay epic and swag!

**Pull request merged**
