### PR TITLE
Added art section (very bare), and a svg recreation of the logo.

### PR DESCRIPTION
**Pull request by schoolchromebookgaming**

### CODE REVIEW

**Review by BombasticTom — COMMENTED** [review]
just link the thing to flash files lmao

**Comment by schoolchromebookgaming** [comment]
@BombasticTom yeah but then you couldn't edit it with vector graphics editors, and only with Flash.
This way it's more accessible

**Comment by BombasticTom** [comment]
i still think you should include it tho, it's literally all of the game files, and you've just included one of them

**Comment by schoolchromebookgaming** [comment]
ok I will add it

**Pull request merged**
